In [ ]:
import pandas as pd

In [ ]:
df_guesses=pd.read_csv('valid_guesses.csv')
df_answers=pd.read_csv('valid_solutions.csv')

In [ ]:
print(df_answers.head())
print(df_guesses.head())

    word
0  aback
1  abase
2  abate
3  abbey
4  abbot
    word
0  aahed
1  aalii
2  aargh
3  aarti
4  abaca

In [ ]:
df_all_words = pd.concat([df_answers, df_guesses], ignore_index=True)

In [ ]:
df_all_words

        word
0      aback
1      abase
2      abate
3      abbey
4      abbot
...      ...
12967  zuzim
12968  zygal
12969  zygon
12970  zymes
12971  zymic

[12972 rows x 1 columns]

In [ ]:
df_all_words.to_csv('all_words.csv', index=False)

In [ ]:
df=pd.read_csv('all_words.csv')
df

        word
0      aback
1      abase
2      abate
3      abbey
4      abbot
...      ...
12967  zuzim
12968  zygal
12969  zygon
12970  zymes
12971  zymic

[12972 rows x 1 columns]

In [ ]:
df_freq=pd.read_csv('unigram_freq.csv')

In [ ]:
df_freq

           word        count
0           the  23135851162
1            of  13151942776
2           and  12997637966
3            to  12136980858
4             a   9081174698
...         ...          ...
333328    gooek        12711
333329   gooddg        12711
333330  gooblle        12711
333331   gollgo        12711
333332    golgw        12711

[333333 rows x 2 columns]

In [ ]:
df_joined=pd.merge(df,df_freq,on='word',how='left')

In [ ]:
df_joined

        word      count
0      aback   272920.0
1      abase    29383.0
2      abate   470646.0
3      abbey  4224864.0
4      abbot   992552.0
...      ...        ...
12967  zuzim        NaN
12968  zygal        NaN
12969  zygon    15300.0
12970  zymes    24137.0
12971  zymic    30459.0

[12972 rows x 2 columns]

In [ ]:
df_joined=df_joined.fillna(1)

In [ ]:
df_joined.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12972 entries, 0 to 12971
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   word    12972 non-null  object
 1   count   12972 non-null  float64
dtypes: float64(1), object(1)
memory usage: 202.8+ KB

In [ ]:
df_joined[df_joined['count']==1.0]

        word  count
2282   wooer    1.0
2315   aahed    1.0
2316   aalii    1.0
2320   abaci    1.0
2321   abacs    1.0
...      ...    ...
12960  zowee    1.0
12964  zupas    1.0
12966  zurfs    1.0
12967  zuzim    1.0
12968  zygal    1.0

[4880 rows x 2 columns]

In [ ]:
df_joined.to_csv('word_frequency.csv',index=False)

In [ ]:
df=pd.read_csv('word_frequency.csv')
df

        word      count
0      aback   272920.0
1      abase    29383.0
2      abate   470646.0
3      abbey  4224864.0
4      abbot   992552.0
...      ...        ...
12967  zuzim        1.0
12968  zygal        1.0
12969  zygon    15300.0
12970  zymes    24137.0
12971  zymic    30459.0

[12972 rows x 2 columns]